# Generated by Django 6.0.2 on 2026-02-11 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0004_ordenservicio_fecha_diagnostico_and_more'),
        ('tecnicos', '0002_tecnico_eliminado_tecnico_fecha_eliminacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('SMS', 'Mensaje de Texto'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Notificación Push'), ('TELEFONO', 'Llamada Telefónica')], max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Canal de Notificación',
                'verbose_name_plural': 'Canales de Notificación',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='AlertaTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('DEMORA', 'Demora en Reparación'), ('REPUESTO_FALTANTE', 'Repuesto Faltante'), ('PROBLEMA_ADICIONAL', 'Problema Adicional Encontrado'), ('EQUIPO_NO_REPARABLE', 'Equipo No Reparable'), ('REQUIERE_AUTORIZACION', 'Requiere Autorización Cliente'), ('CAMBIO_FECHA', 'Cambio de Fecha Estimada'), ('DISPONIBILIDAD', 'Cambio de Disponibilidad')], max_length=30)),
                ('descripcion', models.TextField()),
                ('nueva_fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('dias_demora', models.IntegerField(blank=True, null=True)),
                ('requiere_atencion', models.BooleanField(default=True)),
                ('atendida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='ordenes.ordenservicio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Alerta de Técnico',
                'verbose_name_plural': 'Alertas de Técnicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('EN_SERVICIO', 'En Servicio Externo'), ('NO_DISPONIBLE', 'No Disponible'), ('VACACIONES', 'De Vacaciones')], default='DISPONIBLE', max_length=20)),
                ('ordenes_activas', models.IntegerField(default=0)),
                ('capacidad_maxima', models.IntegerField(default=5, help_text='Máximo de órdenes simultáneas')),
                ('notas', models.TextField(blank=True, help_text='Razón del estado actual')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('disponible_desde', models.DateTimeField(blank=True, null=True)),
                ('tecnico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_actual', to='tecnicos.tecnico')),
            ],
            options={
                'verbose_name': 'Estado de Técnico',
                'verbose_name_plural': 'Estados de Técnicos',
            },
        ),
        migrations.CreateModel(
            name='MonitoreoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_monitoreo', models.DateTimeField(auto_now_add=True)),
                ('alerta_3_dias', models.BooleanField(default=False, help_text='Alerta 3 días antes del vencimiento')),
                ('alerta_1_dia', models.BooleanField(default=False, help_text='Alerta 1 día antes del vencimiento')),
                ('alerta_vencida', models.BooleanField(default=False, help_text='Alerta cuando se vence')),
                ('ultima_actualizacion_cliente', models.DateTimeField(blank=True, null=True)),
                ('notificaciones_enviadas', models.IntegerField(default=0)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreo', to='ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'Monitoreo de Orden',
                'verbose_name_plural': 'Monitoreo de Órdenes',
            },
        ),
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254, verbose_name='Correo destinatario')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('contenido_texto', models.TextField(verbose_name='Contenido texto plano')),
                ('contenido_html', models.TextField(blank=True, verbose_name='Contenido HTML')),
                ('tipo_notificacion', models.CharField(choices=[('REPORTE_CLIENTE', 'Envío de reporte de cliente'), ('ASIGNACION_TECNICO', 'Envío de equipo'), ('ORDEN_SERVICIO_CLIENTE', 'Orden de Servicio'), ('DIAGNOSTICO_COMPLETADO', 'Diagnóstico Completado'), ('EQUIPO_LISTO', 'Equipo Listo para Entrega')], max_length=30, verbose_name='Tipo')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('error_mensaje', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails_enviados', to='ordenes.ordenservicio', verbose_name='Orden de servicio')),
            ],
            options={
                'verbose_name': 'Notificación por Email',
                'verbose_name_plural': 'Notificaciones por Email',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('TECNICO', 'Técnico'), ('CLIENTE', 'Cliente'), ('ADMINISTRADOR', 'Administrador')], max_length=20)),
                ('evento', models.CharField(choices=[('ORDEN_CREADA', 'Orden Creada'), ('ORDEN_ASIGNADA', 'Orden Asignada a Técnico'), ('INICIO_DIAGNOSTICO', 'Inicio de Diagnóstico'), ('DIAGNOSTICO_COMPLETADO', 'Diagnóstico Completado'), ('INICIO_REPARACION', 'Inicio de Reparación'), ('REPARACION_COMPLETADA', 'Reparación Completada'), ('DEMORA_REPORTADA', 'Demora Reportada'), ('LISTA_ENTREGA', 'Lista para Entrega'), ('EQUIPO_ENTREGADO', 'Equipo Entregado'), ('ALERTA_FECHA_VENCIMIENTO', 'Alerta de Fecha Próxima a Vencer')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('template_mensaje', models.TextField(help_text='Usar {variables} para personalizar')),
                ('canales', models.ManyToManyField(to='notificaciones.canalnotificacion')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'unique_together': {('tipo_usuario', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario_tipo', models.CharField(max_length=20)),
                ('destinatario_id', models.IntegerField()),
                ('destinatario_nombre', models.CharField(max_length=200)),
                ('evento', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('LEIDA', 'Leída'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('fecha_programada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('intentos', models.IntegerField(default=0)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notificaciones.canalnotificacion')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='ordenes.ordenservicio')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'ordering': ['-fecha_programada'],
                'indexes': [models.Index(fields=['estado', 'fecha_programada'], name='notificacio_estado_d52a82_idx'), models.Index(fields=['orden', 'destinatario_tipo'], name='notificacio_orden_i_6fa5a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificacionWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('INFO', 'Información'), ('SUCCESS', 'Éxito'), ('WARNING', 'Advertencia'), ('DANGER', 'Peligro'), ('PRIMARY', 'Primario')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('icono', models.CharField(default='fa-bell', help_text='Clase de Font Awesome', max_length=50, verbose_name='Icono')),
                ('url', models.CharField(blank=True, help_text='URL a la que redirigir al hacer clic', max_length=200, verbose_name='URL de acción')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('orden_servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_web', to='ordenes.ordenservicio', verbose_name='Orden de servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_web', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación Web',
                'verbose_name_plural': 'Notificaciones Web',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='notificacio_usuario_04234a_idx'), models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_6bc3b6_idx')],
            },
        ),
    ]
