# Generated by Django 6.0.2 on 2026-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreoorden',
            name='alerta_1_dia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoreoorden',
            name='alerta_3_dias',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitoreoorden',
            name='alerta_vencida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacionweb',
            name='icono',
            field=models.CharField(default='fa-bell', max_length=50, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='notificacionweb',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL de acción'),
        ),
    ]
