# Generated by Django 5.1.3 on 2025-11-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(blank=True, help_text='Generado automáticamente', max_length=20, unique=True, verbose_name='Número de venta'),
        ),
    ]
