# Generated by Django 4.2.9 on 2025-12-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_add_usuario'),
        ('ventas', '0002_alter_venta_numero_venta'),
    ]

    operations = [
    ]
