# Generated by Django 5.1.3 on 2025-11-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de factura')),
                ('tipo_factura', models.CharField(choices=[('VENTA', 'Factura de Venta'), ('SERVICIO', 'Factura de Servicio'), ('MIXTA', 'Factura Mixta')], default='VENTA', max_length=10, verbose_name='Tipo')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='clientes.cliente', verbose_name='Cliente')),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta', verbose_name='Venta relacionada')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
