# Generated by Django 6.0.2 on 2026-02-12 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='Backup Automático Activo')),
                ('frecuencia_horas', models.IntegerField(default=24, verbose_name='Frecuencia (horas)')),
                ('max_backups', models.IntegerField(default=10, verbose_name='Máximo de Backups a Mantener')),
                ('ruta_guardado', models.CharField(default='backups/', max_length=500, verbose_name='Ruta de Guardado')),
                ('incluir_media', models.BooleanField(default=False, verbose_name='Incluir Archivos Media')),
                ('notificar_admin', models.BooleanField(default=True, verbose_name='Notificar al Admin')),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Backup',
                'verbose_name_plural': 'Configuraciones de Backup',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Backup')),
                ('archivo', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('PROGRAMADO', 'Programado')], default='MANUAL', max_length=20)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('EN_PROCESO', 'En Proceso')], default='EN_PROCESO', max_length=20)),
                ('tamaño', models.BigIntegerField(default=0, verbose_name='Tamaño en Bytes')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
