# Generated by Django 4.2.9 on 2025-10-01 18:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_administrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=42)),
                ('correo_electronico', models.EmailField(max_length=40)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('correoElectronico', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Garantias',
            fields=[
                ('id_garantias', models.AutoField(primary_key=True, serialize=False)),
                ('facturacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id_ordenServicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_orden', models.CharField(max_length=255)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=35)),
                ('modelo_producto', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_producto', models.CharField(max_length=45)),
                ('diseño', models.CharField(max_length=40)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit_proveedor', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('cedula', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('especialidad', models.CharField(max_length=40)),
                ('tipo_tecnico', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_vendidas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='ServicioTecnico',
            fields=[
                ('id_servicio_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ordenservicio')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tecnico')),
            ],
            options={
                'verbose_name': 'Servicio Técnico',
                'verbose_name_plural': 'Servicios Técnicos',
            },
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tecnico'),
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_recibo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_factura', models.DateField()),
                ('descripcion_venta', models.CharField(max_length=50)),
                ('terminos_condiciones', models.CharField(max_length=25)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.administrador')),
                ('orden_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ordenservicio')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ventas')),
            ],
            options={
                'verbose_name': 'Facturación',
                'verbose_name_plural': 'Facturaciones',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=25)),
                ('serie', models.CharField(max_length=30)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.marca')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='ComprasMercancia',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_comprada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_compra', models.DateField()),
                ('precio_compra', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.administrador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.proveedor')),
            ],
            options={
                'verbose_name': 'Compra de Mercancía',
                'verbose_name_plural': 'Compras de Mercancía',
            },
        ),
    ]
