# Generated by Django 4.2.9 on 2025-10-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
    ]
