# Generated by Django 4.2.9 on 2025-12-10 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_reaccionproducto'),
        ('main', '0004_cart_category_order_product_orderitem_invoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='numero_telefono',
            new_name='numero_telefonico',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='id_marca',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='correoElectronico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='serie',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_electronico',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
        ),
        migrations.AddField(
            model_name='marca',
            name='color',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='clave',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
