# Generated by Django 5.2.8 on 2025-11-08 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('CLIENTE', 'Cliente'), ('TECNICO', 'Técnico'), ('PROVEEDOR', 'Proveedor')], default='CLIENTE', max_length=10, verbose_name='Tipo de Usuario')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='Documento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto de Perfil')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Usuario Bloqueado')),
                ('motivo_bloqueo', models.TextField(blank=True, verbose_name='Motivo del Bloqueo')),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Bloqueo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_perfil', to='clientes.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'db_table': 'usuarios_perfil',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
