# Generated by Django 4.2.9 on 2026-02-05 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_passwordresettoken_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('ip_solicitud', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperación',
                'verbose_name_plural': 'Tokens de Recuperación',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
