# Generated by Django 4.2.9 on 2025-12-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos', '0001_initial'),
        ('usuarios', '0002_passwordresettoken_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_perfil', to='tecnicos.tecnico'),
        ),
    ]
