# Generated by Django 5.2.8 on 2025-11-08 02:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comprador', models.CharField(max_length=200, verbose_name='Nombre del comprador')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo electrónico')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('factura_compra', models.CharField(blank=True, max_length=50, verbose_name='Número de factura')),
                ('lugar_compra', models.CharField(max_length=200, verbose_name='Lugar de compra')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de garantía')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('meses_garantia', models.IntegerField(default=12, verbose_name='Meses de garantía')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('EN_REVISION', 'En revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('motivo_reclamacion', models.TextField(blank=True, verbose_name='Motivo de reclamación')),
                ('descripcion_problema', models.TextField(blank=True, verbose_name='Descripción del problema')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='clientes.cliente', verbose_name='Cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de seguimiento')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='garantias.garantia', verbose_name='Garantía')),
            ],
            options={
                'verbose_name': 'Seguimiento de Garantía',
                'verbose_name_plural': 'Seguimientos de Garantías',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['cedula'], name='garantias_g_cedula_5c5090_idx'),
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['factura_compra'], name='garantias_g_factura_3ac101_idx'),
        ),
        migrations.AddIndex(
            model_name='garantia',
            index=models.Index(fields=['estado'], name='garantias_g_estado_d9a0ca_idx'),
        ),
    ]
