# Generated by Django 5.1.3 on 2025-11-10 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_capacitacion', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la capacitación')),
                ('tipo', models.CharField(choices=[('TECNICA', 'Capacitación Técnica'), ('SOFTWARE', 'Software'), ('ATENCION_CLIENTE', 'Atención al Cliente'), ('SEGURIDAD', 'Seguridad'), ('OTRA', 'Otra')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('instructor', models.CharField(max_length=150, verbose_name='Instructor')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('duracion_horas', models.IntegerField(verbose_name='Duración (horas)')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('HIBRIDA', 'Híbrida')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('cupo_maximo', models.IntegerField(default=20, verbose_name='Cupo máximo')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo')),
                ('certificado', models.BooleanField(default=True, verbose_name='Otorga certificado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'db_table': 'capacitaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('asistio', models.BooleanField(default=False, verbose_name='Asistió')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Calificación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='capacitaciones.capacitacion', verbose_name='Capacitación')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='tecnicos.tecnico', verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'capacitaciones_participantes',
                'unique_together': {('capacitacion', 'tecnico')},
            },
        ),
    ]
