# Generated by Django 5.1.3 on 2025-11-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_equipo', models.CharField(max_length=20, unique=True, verbose_name='Código de equipo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del equipo')),
                ('tipo_equipo', models.CharField(choices=[('COMPUTADOR', 'Computador'), ('LAPTOP', 'Laptop'), ('IMPRESORA', 'Impresora'), ('SERVIDOR', 'Servidor'), ('ROUTER', 'Router'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones técnicas')),
                ('fecha_adquisicion', models.DateField(verbose_name='Fecha de adquisición')),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de adquisición')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_REPARACION', 'En Reparación'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('ASIGNADO', 'Asignado'), ('DISPONIBLE', 'Disponible')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('responsable', models.CharField(blank=True, max_length=150, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
                'ordering': ['codigo_equipo'],
            },
        ),
    ]
