# Generated by Django 4.2.9 on 2025-11-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'PC de Escritorio'), ('TABLET', 'Tablet'), ('CELULAR', 'Celular'), ('IMPRESORA', 'Impresora'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('procesador', models.CharField(blank=True, max_length=100, verbose_name='Procesador')),
                ('memoria_ram', models.CharField(blank=True, max_length=50, verbose_name='Memoria RAM')),
                ('almacenamiento', models.CharField(blank=True, max_length=50, verbose_name='Almacenamiento')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operativo')),
                ('fecha_compra', models.DateField(blank=True, null=True, verbose_name='Fecha de Compra')),
                ('factura_compra', models.CharField(blank=True, max_length=100, verbose_name='Factura de Compra')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_REPARACION', 'En Reparación'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
