# Generated by Django 5.2.8 on 2025-11-08 02:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('modelo_equipo', models.CharField(blank=True, max_length=100, verbose_name='Modelo del equipo')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('procesador', models.CharField(blank=True, max_length=100, verbose_name='Procesador')),
                ('memoria_ram', models.CharField(blank=True, max_length=50, verbose_name='Memoria RAM')),
                ('memoria_rom', models.CharField(blank=True, max_length=50, verbose_name='Memoria ROM/Almacenamiento')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones técnicas')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de compra')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de venta')),
                ('precio_mayorista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio mayorista')),
                ('stock_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock actual')),
                ('stock_minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock mínimo')),
                ('stock_maximo', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock máximo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto')),
                ('disponible_web', models.BooleanField(default=True, verbose_name='Disponible en web')),
                ('destacado', models.BooleanField(default=False, verbose_name='Producto destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tiene_garantia', models.BooleanField(default=True, verbose_name='Tiene garantía')),
                ('meses_garantia', models.IntegerField(default=12, verbose_name='Meses de garantía')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoriaproducto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=20, verbose_name='Tipo de movimiento')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('stock_anterior', models.IntegerField(verbose_name='Stock anterior')),
                ('stock_nuevo', models.IntegerField(verbose_name='Stock nuevo')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del movimiento')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_sku'], name='productos_p_codigo__9a5e79_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre_producto'], name='productos_p_nombre__74612e_idx'),
        ),
    ]
