# Generated by Django 4.2.9 on 2025-11-14 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaccionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de sesión')),
                ('tipo', models.CharField(choices=[('like', 'Me gusta'), ('dislike', 'No me gusta')], max_length=10, verbose_name='Tipo de reacción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacciones', to='productos.producto', verbose_name='Producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reacción de Producto',
                'verbose_name_plural': 'Reacciones de Productos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto', 'session_id'), ('producto', 'usuario')},
            },
        ),
    ]
