# Generated by Django 5.2.8 on 2025-11-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_numero__b55e8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='clientes_fecha_r_3d3e65_idx',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
