# Generated by Django 5.2.8 on 2025-11-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_clientes_numero__b55e8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
    ]
