# Generated by Django 4.2.9 on 2026-02-04 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=50, unique=True)),
                ('fecha_reporte', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_dano', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Daño',
                'verbose_name_plural': 'Registros de Daños',
            },
        ),
        migrations.CreateModel(
            name='NotaDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('es_publica', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='reportes_dano.registrodano')),
            ],
            options={
                'verbose_name': 'Nota de Daño',
                'verbose_name_plural': 'Notas de Daños',
            },
        ),
        migrations.CreateModel(
            name='ImagenDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reportes_dano/')),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reportes_dano.registrodano')),
            ],
            options={
                'verbose_name': 'Imagen de Daño',
                'verbose_name_plural': 'Imágenes de Daños',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('PDF', 'PDF'), ('TXT', 'TXT')], max_length=10)),
                ('archivo', models.FileField(upload_to='facturas_dano/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='reportes_dano.registrodano')),
            ],
            options={
                'verbose_name': 'Documento de Factura',
                'verbose_name_plural': 'Documentos de Facturas',
            },
        ),
    ]
