# Generated by Django 4.2.9 on 2026-02-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('reportes_dano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodano',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_dano', to='ordenes.ordenservicio', verbose_name='Orden de Servicio'),
        ),
    ]
