# Generated by Django 6.0.2 on 2026-02-11 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
        ('equipos', '0002_equipo_cliente'),
        ('reportes_dano', '0002_registrodano_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodano',
            options={'ordering': ['-fecha_reporte'], 'verbose_name': 'Registro de Daño', 'verbose_name_plural': 'Registros de Daños'},
        ),
        migrations.RemoveField(
            model_name='registrodano',
            name='numero_factura',
        ),
        migrations.AddField(
            model_name='registrodano',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_dano', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_dano', to='equipos.equipo', verbose_name='Equipo'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REVISADO', 'Revisado por Admin'), ('ASIGNADO', 'Asignado a Técnico'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='fecha_notificacion_admin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha notificación admin'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='notificado_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador notificado'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='numero_reporte',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de reporte'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='registrodano',
            name='tiempo_requerido_cliente',
            field=models.CharField(blank=True, help_text='Cuándo necesita el equipo', max_length=200, verbose_name='Tiempo requerido por cliente'),
        ),
        migrations.AlterField(
            model_name='registrodano',
            name='descripcion_dano',
            field=models.TextField(verbose_name='Descripción del daño'),
        ),
        migrations.AlterField(
            model_name='registrodano',
            name='fecha_reporte',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
        ),
        migrations.AlterField(
            model_name='registrodano',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reportó'),
        ),
        migrations.AlterModelTable(
            name='registrodano',
            table='reportes_dano',
        ),
    ]
