# Generated by Django 5.1.3 on 2025-11-10 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+-?\\d*$', 'Ingrese un NIT válido')], verbose_name='NIT')),
                ('nombre_contacto', models.CharField(max_length=150, verbose_name='Nombre del contacto')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Ingrese un número válido')], verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('productos_servicios', models.TextField(blank=True, help_text='Descripción de lo que suministra el proveedor', verbose_name='Productos/Servicios que ofrece')),
                ('condiciones_pago', models.CharField(blank=True, help_text='Ej: 30 días, contado, etc.', max_length=100, verbose_name='Condiciones de pago')),
                ('tiempo_entrega', models.CharField(blank=True, help_text='Tiempo promedio de entrega', max_length=50, verbose_name='Tiempo de entrega')),
                ('calificacion', models.IntegerField(choices=[(1, '⭐ Malo'), (2, '⭐⭐ Regular'), (3, '⭐⭐⭐ Bueno'), (4, '⭐⭐⭐⭐ Muy Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')], default=3, verbose_name='Calificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre_empresa'],
            },
        ),
    ]
