# Generated by Django 4.2.9 on 2025-11-10 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='NIT', max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo se permiten números')], verbose_name='Número de Documento')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Ingrese un número de teléfono válido')], verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('contacto_principal', models.CharField(blank=True, max_length=150, verbose_name='Contacto Principal')),
                ('telefono_contacto', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de Contacto')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
