# Generated by Django 4.2.9 on 2025-11-10 14:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_compromiso', models.DateField(blank=True, null=True, verbose_name='Fecha de Compromiso')),
                ('tipo_equipo', models.CharField(max_length=100, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('falla_reportada', models.TextField(verbose_name='Falla Reportada por el Cliente')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico Técnico')),
                ('solucion', models.TextField(blank=True, verbose_name='Solución Aplicada')),
                ('accesorios', models.TextField(blank=True, verbose_name='Accesorios Incluidos')),
                ('estado_fisico', models.TextField(blank=True, verbose_name='Estado Físico del Equipo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('DIAGNOSTICADA', 'Diagnosticada'), ('REPARADA', 'Reparada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Mano de Obra')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de Repuestos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='clientes.cliente', verbose_name='Cliente')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='tecnicos.tecnico', verbose_name='Técnico Asignado')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción del Seguimiento')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, verbose_name='Estado Nuevo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ordenes.ordenservicio', verbose_name='Orden de Servicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Orden',
                'verbose_name_plural': 'Seguimientos de Órdenes',
                'ordering': ['-fecha'],
            },
        ),
    ]
