# Generated by Django 5.1.3 on 2025-11-10 22:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_observaciones'),
        ('productos', '0001_initial'),
        ('tecnicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(help_text='Generado automáticamente', max_length=20, unique=True, verbose_name='Número de orden')),
                ('tipo_equipo', models.CharField(help_text='Ej: Laptop, PC, Impresora', max_length=100, verbose_name='Tipo de equipo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('falla_reportada', models.TextField(verbose_name='Falla reportada por el cliente')),
                ('estado_fisico', models.TextField(blank=True, help_text='Descripción del estado físico al recibir', verbose_name='Estado físico del equipo')),
                ('accesorios_incluidos', models.TextField(blank=True, help_text='Ej: Cargador, mouse, bolso, etc.', verbose_name='Accesorios incluidos')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico técnico')),
                ('solucion_aplicada', models.TextField(blank=True, verbose_name='Solución aplicada')),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('EN_DIAGNOSTICO', 'En Diagnóstico'), ('DIAGNOSTICADA', 'Diagnosticada'), ('EN_REPARACION', 'En Reparación'), ('REPARADA', 'Reparada'), ('EN_ESPERA_REPUESTOS', 'Esperando Repuestos'), ('EN_ESPERA_CLIENTE', 'Esperando Cliente'), ('LISTA_ENTREGA', 'Lista para Entrega'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='RECIBIDA', max_length=25, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('costo_diagnostico', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo de diagnóstico')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo mano de obra')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo repuestos')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo total')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('fecha_compromiso', models.DateTimeField(blank=True, help_text='Fecha estimada de entrega', null=True, verbose_name='Fecha de compromiso')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tiene_garantia', models.BooleanField(default=True, verbose_name='Tiene garantía')),
                ('dias_garantia', models.IntegerField(default=30, verbose_name='Días de garantía')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('notas_internas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente', verbose_name='Cliente')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to='tecnicos.tecnico', verbose_name='Técnico asignado')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'db_table': 'ordenes_servicio',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='ordenes.ordenservicio', verbose_name='Orden de servicio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='productos.producto', verbose_name='Producto/Repuesto')),
            ],
            options={
                'verbose_name': 'Repuesto de Orden',
                'verbose_name_plural': 'Repuestos de Órdenes',
                'db_table': 'ordenes_repuestos',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=25, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=25, verbose_name='Estado nuevo')),
                ('descripcion', models.TextField(verbose_name='Descripción del cambio')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='ordenes.ordenservicio', verbose_name='Orden de servicio')),
            ],
            options={
                'verbose_name': 'Seguimiento de Orden',
                'verbose_name_plural': 'Seguimientos de Órdenes',
                'db_table': 'ordenes_seguimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['numero_orden'], name='ordenes_ser_numero__9f2013_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['cliente', 'fecha_recepcion'], name='ordenes_ser_cliente_da48f1_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['estado'], name='ordenes_ser_estado_1b43e4_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenservicio',
            index=models.Index(fields=['tecnico_asignado'], name='ordenes_ser_tecnico_670b1b_idx'),
        ),
    ]
