# Generated by Django 4.2.9 on 2026-02-05 11:47

from django.db import migrations, models
from decimal import Decimal
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        # Cambiar campos de costos en OrdenServicio a decimal sin decimales
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_diagnostico',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Costo de diagnóstico'
            ),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_mano_obra',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Costo mano de obra'
            ),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_repuestos',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal('0'))],
                verbose_name='Costo repuestos'
            ),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_total',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name='Costo total'
            ),
        ),
        # Cambiar campos en RepuestoOrden
        migrations.AlterField(
            model_name='repuestoorden',
            name='precio_unitario',
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                verbose_name='Precio unitario'
            ),
        ),
        migrations.AlterField(
            model_name='repuestoorden',
            name='subtotal',
            field=models.DecimalField(
                decimal_places=0,
                max_digits=12,
                verbose_name='Subtotal'
            ),
        ),
    ]
