# Generated by Django 4.2.9 on 2026-02-05 10:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_cambio_precios_colombianos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_diagnostico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo de diagnóstico'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo mano de obra'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_repuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo repuestos'),
        ),
        migrations.AlterField(
            model_name='ordenservicio',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo total'),
        ),
        migrations.AlterField(
            model_name='repuestoorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='repuestoorden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
