# Generated by Django 6.0.2 on 2026-02-11 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_ordenservicio_costo_diagnostico_and_more'),
        ('reportes_dano', '0002_registrodano_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_diagnostico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de diagnóstico'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_notificacion_admin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha notificación admin'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_notificacion_cliente',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha notificación cliente'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='fecha_notificacion_tecnico',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha notificación técnico'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='notificado_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador notificado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='notificado_cliente',
            field=models.BooleanField(default=False, verbose_name='Cliente notificado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='notificado_tecnico',
            field=models.BooleanField(default=False, verbose_name='Técnico notificado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='reporte_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orden_servicio_generada', to='reportes_dano.registrodano', verbose_name='Reporte relacionado'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tiempo_estimado_reparacion',
            field=models.IntegerField(blank=True, help_text='Estimación del técnico en horas', null=True, verbose_name='Tiempo estimado de reparación (horas)'),
        ),
        migrations.AddField(
            model_name='ordenservicio',
            name='tiempo_requerido_cliente',
            field=models.CharField(blank=True, help_text='Tiempo en que el cliente necesita el equipo', max_length=200, verbose_name='Tiempo requerido por cliente'),
        ),
    ]
